version: '3'

volumes:
  postgres-data:

services:
  debezium:
    image: debezium/connect:0.8
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVER=${PUBLIC_NODE_IP}:30002
      - GROUP_ID=debezium-connect-sink
      - CONFIG_STORAGE_TOPIC=debezium-connect-sink_config
      - OFFSET_STORAGE_TOPIC=debezium-connect-sink_offset

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data